services:
  payment-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: paymentdb
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3309:3306"
    volumes:
      - payment-db-data:/var/lib/mysql
    networks:
      - payment-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 20s

  payment-api:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      payment-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://payment-db:3306/paymentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge

volumes:
  payment-db-data:
